# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the Gradle Daemon.
# Setting a larger heap size helps with memory-intensive tasks like dexing.
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# AndroidX enables the use of libraries from the Jetpack suite.
android.useAndroidX=true

# Kotlin code style for the project.
kotlin.code.style=official
